services:
  - type: web
    name: trainerize-fitness-program
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn webhook_server:app --timeout 180 --workers 1 --worker-class sync --worker-connections 1000 --max-requests 100 --max-requests-jitter 10 --preload"
    plan: free
    healthCheckPath: /health
    numInstances: 1
    envVars:
      - key: QDRANT_URL
        sync: false
      - key: QDRANT_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: TRAINERIZE_FIND
        sync: false
      - key: TRAINERIZE_WORKOUT_ADD
        sync: false
      - key: TRAINERIZE_PROGRAM_ADD
        sync: false
      - key: TRAINERIZE_AUTH
        sync: false
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: WEB_CONCURRENCY
        value: "1" 